import "./globals.css";

import type { Metadata } from "next";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      {/*
        flex-col: Stacks elements vertically
        min-h-screen: Forces body to be at least as tall as the browser window
      */}
      <body className="flex flex-col min-h-screen antialiased">
        <ThemeProvider>
          <Header/>

          {/*
            flex-grow: This tells the main content to take up ALL available
            space, pushing the footer to the bottom.
          */}
          <main className="m3-container flex-grow">
            {children}
          </main>
          
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
